version: '3'

services:
  web:
    build: .
    volumes:
      - "./app:/app"
      - "./public:/public"
      - "./_secrets:/app/utilities/data"

    command: npm start
    ports:
      - "9014:5000"
    restart: unless-stopped
    container_name: iahspeu-apiserver
    environment:
      APP_PORT: 5000
      APP_HOSTNAME: '0.0.0.0'
      APP_ENVIRONMENT: 'dev'
      CORS_WHITELIST: '["http://localhost:4200", "https://members.iahspeurope.com", "https://members-staging.iahspeurope.com"]'
    networks:
      - sh-dev

networks:
  sh-dev:
    external: true
