version: '3'

services:
  web:
    image: iahspeu-api:0.0.2
    volumes:
      - "./_secrets:/app/utilities/data"

    command: npm start
    ports:
      - "9014:80"
    restart: unless-stopped
    container_name: iahspeu-apiserver
    environment:
      APP_PORT: 80
      APP_HOSTNAME: '0.0.0.0'
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
