version: '3'

services:
  web:
    build: .
    volumes:
      - "./_secrets:/app/utilities/data"

    command: npm start
    ports:
      - "9014:5000"
    restart: unless-stopped
    container_name: iahspeu-apiserver
    environment:
      APP_PORT: 5000
      APP_HOSTNAME: '0.0.0.0'
    networks:
      - sh-dev

networks:
  sh-dev:
    external: true
